# Generated by Django 5.1.15 on 2026-09-12 06:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=11)),
                ('code', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'کد یک\u200cبارمصرف',
                'verbose_name_plural': 'کدهای یک\u200cبارمصرف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شمارهٔ موبایل')),
                ('display_name', models.CharField(blank=True, max_length=60, verbose_name='نام نمایشی')),
                ('account_type', models.CharField(choices=[('parent', 'والد (شخصی)'), ('pro', 'فروشندهٔ حرفه\u200cای'), ('official', 'حساب رسمی وندرکیدز')], default='parent', max_length=10, verbose_name='نوع حساب')),
                ('is_verified', models.BooleanField(default=False, verbose_name='شمارهٔ تأییدشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی پنل')),
                ('is_banned', models.BooleanField(default=False, verbose_name='مسدود')),
                ('ban_reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل مسدودی')),
                ('listing_cap', models.PositiveSmallIntegerField(default=5, verbose_name='سقف آگهی فعال')),
                ('notify_moderation', models.BooleanField(default=True, verbose_name='پیامک نتیجهٔ بررسی')),
                ('notify_chat', models.BooleanField(default=True, verbose_name='پیامک پیام جدید')),
                ('notify_saved_search', models.BooleanField(default=False, verbose_name='پیامک جستجوی ذخیره\u200cشده')),
                ('warnings_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد اخطار')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.city', verbose_name='شهر')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.district', verbose_name='محلهٔ پیش\u200cفرض')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('querystring', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جستجوی ذخیره\u200cشده',
                'verbose_name_plural': 'جستجوهای ذخیره\u200cشده',
            },
        ),
    ]
