# Generated by Django 5.1.15 on 2026-09-12 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'تأیید'), ('reject', 'رد'), ('takedown', 'حذف'), ('warn', 'اخطار'), ('ban', 'مسدودسازی'), ('dismiss', 'بی\u200cاشکال')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('listing_title', models.CharField(blank=True, max_length=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='listings.listing')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='listings.report')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تصمیم بررسی',
                'verbose_name_plural': 'تصمیم\u200cهای بررسی',
                'ordering': ['-created_at'],
            },
        ),
    ]
