# Generated by Django 5.1.15 on 2026-09-12 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('kind', models.CharField(choices=[('promote', 'نردبان / آگهی ویژه'), ('subscription', 'اشتراک فروشنده'), ('badge', 'نشان فروشنده')], max_length=15)),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت (تومان)')),
                ('duration_days', models.PositiveSmallIntegerField(default=7, verbose_name='مدت (روز)')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پلن',
                'verbose_name_plural': 'پلن\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ (تومان)')),
                ('gateway', models.CharField(max_length=20)),
                ('authority', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شناسهٔ درگاه')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شد'), ('failed', 'ناموفق'), ('canceled', 'لغو شد')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.plan')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
