# Generated by Django 5.1.15 on 2026-09-12 06:46

import apps.listings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.listings.models._code, max_length=8, unique=True, verbose_name='کد آگهی')),
                ('type', models.CharField(choices=[('sell', 'فروش'), ('free', 'رایگان'), ('donate', 'اهدا به خیریه'), ('wanted', 'دنبالش می\u200cگردم'), ('swap', 'معاوضه'), ('rent', 'اجارهٔ نفر به نفر')], default='sell', max_length=10, verbose_name='نوع آگهی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تأیید'), ('live', 'منتشر شده'), ('rejected', 'رد شد'), ('paused', 'متوقف'), ('sold', 'فروخته شد'), ('expired', 'منقضی'), ('removed', 'حذف\u200cشده')], db_index=True, default='draft', max_length=10, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=90, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120)),
                ('age_range', models.CharField(choices=[('0-1', '۰ تا ۱ سال'), ('1-3', '۱ تا ۳ سال'), ('3-5', '۳ تا ۵ سال'), ('5-8', '۵ تا ۸ سال'), ('8+', 'بالای ۸ سال')], max_length=4, verbose_name='ردهٔ سنی')),
                ('condition', models.CharField(choices=[('new', 'نو'), ('likenew', 'در حد نو'), ('used', 'کارکردهٔ سالم'), ('repair', 'نیاز به تعمیر')], max_length=8, verbose_name='وضعیت کالا')),
                ('is_complete', models.BooleanField(default=True, verbose_name='همهٔ قطعات موجود')),
                ('has_box', models.BooleanField(default=False, verbose_name='جعبهٔ اصلی')),
                ('has_manual', models.BooleanField(default=False, verbose_name='دفترچهٔ راهنما')),
                ('has_battery', models.BooleanField(default=False, verbose_name='باتری/شارژر همراه')),
                ('missing_parts', models.BooleanField(default=False, verbose_name='چند قطعه کم دارد')),
                ('hygiene_note', models.CharField(max_length=200, verbose_name='یادداشت بهداشتی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='مشخصات تکمیلی')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت (تومان)')),
                ('original_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت نو (تومان)')),
                ('is_negotiable', models.BooleanField(default=True, verbose_name='قابل مذاکره')),
                ('meetup_hint', models.CharField(blank=True, max_length=120, verbose_name='محل پیشنهادی تحویل')),
                ('allow_chat', models.BooleanField(default=True, verbose_name='چت فعال')),
                ('allow_phone', models.BooleanField(default=True, verbose_name='نمایش شماره')),
                ('attested_safe', models.BooleanField(default=False, verbose_name='تأیید ایمنی و بدون عکس کودک')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='نردبان/ویژه')),
                ('promoted_until', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('reveals_count', models.PositiveIntegerField(default=0, verbose_name='نمایش شماره')),
                ('search_text', models.TextField(blank=True, editable=False)),
                ('auto_flags', models.JSONField(blank=True, default=list, verbose_name='هشدارهای خودکار')),
                ('reject_reason', models.CharField(blank=True, max_length=200, verbose_name='دلیل رد')),
                ('reject_note', models.TextField(blank=True, verbose_name='توضیح رد')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال برای بررسی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضا')),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.category', verbose_name='دسته\u200cبندی')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.city', verbose_name='شهر')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.district', verbose_name='محله')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی\u200cها',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/', verbose_name='عکس (گالری)')),
                ('thumb', models.ImageField(blank=True, upload_to='listings/%Y/%m/thumbs/', verbose_name='بندانگشتی')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'verbose_name': 'عکس آگهی',
                'verbose_name_plural': 'عکس\u200cهای آگهی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PhoneReveal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveals', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_reveals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نمایش شماره',
                'verbose_name_plural': 'نمایش\u200cهای شماره',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', 'مشکوک به کلاهبرداری (درخواست بیعانه)'), ('mismatch', 'وضعیت واقعی با آگهی نمی\u200cخواند'), ('prohibited', 'کالای ممنوعه یا ناایمن'), ('child_photo', 'عکس کودک در آگهی'), ('abuse', 'پیام توهین\u200cآمیز'), ('spam', 'اسپم / تکراری'), ('other', 'موارد دیگر')], max_length=20, verbose_name='نوع گزارش')),
                ('note', models.TextField(blank=True, verbose_name='توضیح')),
                ('priority', models.CharField(choices=[('urgent', 'فوری'), ('normal', 'متوسط'), ('low', 'کم')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'باز'), ('resolved', 'رسیدگی شد'), ('dismissed', 'بی\u200cاشکال')], default='open', max_length=10)),
                ('resolution', models.CharField(blank=True, max_length=200, verbose_name='اقدام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.conversation')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آگهی ذخیره\u200cشده',
                'verbose_name_plural': 'آگهی\u200cهای ذخیره\u200cشده',
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'city', 'category'], name='listings_li_status_efa3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'published_at'], name='listings_li_status_ffd407_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedlisting',
            unique_together={('user', 'listing')},
        ),
    ]
