# Generated by Django 5.1.15 on 2026-09-12 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True, verbose_name='نمایش در صفحهٔ اصلی')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=8, verbose_name='ایموجی')),
                ('color', models.CharField(blank=True, default='var(--amber-100)', max_length=40, verbose_name='رنگ پس\u200cزمینه (CSS)')),
                ('ph_class', models.CharField(default='ph-a', max_length=8, verbose_name='کلاس placeholder')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('safety_tips', models.TextField(blank=True, verbose_name='نکات ایمنی (هر خط یک مورد، «ایموجی|متن»)')),
                ('seo_title', models.CharField(blank=True, max_length=120)),
                ('seo_description', models.CharField(blank=True, max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام محله')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='catalog.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'محله',
                'verbose_name_plural': 'محله\u200cها',
                'ordering': ['order', 'name'],
                'unique_together': {('city', 'slug')},
            },
        ),
    ]
